# lab_one.toml
# Enter the Q&A for each lab here
[config]
step_one = "Open the terminal on your Linux system."
step_one_answer = "ls"
step_two = "Check what user you are logged into. Is it root?"
step_two_answer = "whoami"
step_three = "Let's create a new user. Name the new user 'john1'."
step_three_answer = "sudo adduser john1"
step_four = "Create another user under the name of 'jane1'."
step_four_answer = "sudo adduser jane1"
step_five = "Create a new user group called 'developers'."
step_five_answer = "sudo addgroup developers"
step_six = "Create a new user group called 'sys-admin'."
step_six_answer = "sudo addgroup sys-admin"
step_seven = "Add the user 'john1' to the 'developers' group."
step_seven_answer = "sudo usermod -G developers john1"
step_eight = "Verify that 'john1' was added to the correct group."
step_eight_answer = "groups john1"
step_nine = "Add the user 'jane1' to the 'sys-admin' group."
step_nine_answer = "sudo usermod -G sys-admin jane1"
step_ten = "Verify that 'jane1' was added to the correct group."
step_ten_answer = "groups jane1"
step_eleven = "Create a new text file called 'lab_file'."
step_eleven_answer = "touch lab_file.txt"
step_twelve = "Check the file permissions for the file you just created."
step_twelve_answer = "ls -l lab_file.txt"
step_thirteen = "Give only the owner read and write permissions, and remove all permissions for everyone else on 'lab_file.txt'."
step_thirteen_answer = "sudo chmod 600 lab_file.txt"
step_fourteen = "Check that the file permissions have been set correctly."
step_fourteen_answer = "ls -l lab_file.txt"
step_fifteen = "Allow the owner to read, write, and execute, and the groups to read and execute, while others have no permissions on 'lab_file.txt'."
step_fifteen_answer = "sudo chmod 750 lab_file.txt"
step_sixteen = "Check that the file permissions have been set correctly."
step_sixteen_answer = "ls -l lab_file.txt"
step_seventeen = "Change the owner of 'lab_file.txt' to 'jane1'."
step_seventeen_answer = "sudo chown jane1 lab_file.txt"
